# network architecture
# encoder related
etype: vggblstm     # encoder architecture type
elayers: 4
eunits: 1024
eprojs: 2048
subsample: "1_1_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 2
dunits: 1024
# attention related
atype: location
adim: 1024
awin: 5
aheads: 4
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.0

# label smoothing
lsm-type: unigram
lsm-weight: 0.1

# context-residual: true

# minibatch related
batch-size: 24
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# other config
dropout-rate: 0.1
dropout-rate-decoder: 0.1

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 10
patience: 0
accum-grad: 1
eps: 5e-9
eps-decay: 1.0


# scheduled sampling option
sampling-probability: 0.0
