# network architecture
backend: pytorch
model-module: espnet.nets.pytorch_backend.e2e_asr_cfmlas:E2E
# encoder related
elayers: 16
eunits: 2048
eprojs: 512 # this must equal to transformer-adim
transformer-adim: 512
transformer-aheads: 4
transformer-attn-dropout-rate: 0.0
transformer-input-layer: conv2d
transformer-encoder-activation-type: swish
transformer-encoder-pos-enc-layer-type: rel_pos
transformer-encoder-selfattn-layer-type: rel_selfattn
macaron-style: true
use-cnn-module: true
cnn-module-kernel: 31
# decoder related
dlayers: 1
dunits: 1024
# attention related
adim: 1024
atype: location
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.0

# label smoothing
lsm-type: unigram
lsm-weight: 0.1
dropout-rate: 0.1
dropout-rate-decoder: 0.1
weight-decay: 0.0
# ema-decay: 0.999
context-residual: true

# minibatch related
batch-size: 20
maxlen-in: 800
maxlen-out: 150
maxioratio: 300
minioratio: 6

# optimization related
sortagrad: 0
accum-grad: 5
grad-clip: 5
opt: noam
epochs: 120
patience: 0
weight-noise-std: 0.00
weight-noise-start: 30000
transformer-lr: 2.5
transformer-warmup-steps: 25000

# scheduled sampling option
sampling-probability: 0.0
# report-interval-iters: 1

# KB related
meetingpath: /home/dawna/gs534/espnet-debug/egs/librispeech/debug_960/data/KBs/LibriKBRare_unigram600suffix/rareword_f120.txt
# meetingpath: /home/dawna/gs534/espnet-debug/egs/librispeech/debug_960/data/KBs/LibriKB1000noise_unigram600suffix
# meetingpath: /home/dawna/gs534/espnet-debug/egs/librispeech/debug_960/data/KBs/LibriKB1000AcousticSim_unigram600suffix
meetingKB: true
lm-odim: 256
dictfile: /home/dawna/gs534/espnet-debug/egs/librispeech/debug_960/data/KBs/bpe_dict_unigram600suffix.txt
KBlextree: true
PtrGen: true
PtrSche: 8
# PtrKBin: true
# init-full-model: /home/dawna/gs534/espnet-debug/egs/librispeech/debug_960/exp/init_models/baseline.ep.15
# init-full-model: exp/librispeech_train_baseline_spec/results/model.acc.best
acousticonly: true
attn_dim: 256
KBmaxlen: 1000
KBminlen: 1000
randomKBsample: true
# DBinput: true
# DBmask: 0.1
DBdrop: 0.3
# smoothprob: 0.0
# dynamicKBs: 1
treetype: jknetcomb3
# treehid: 256
# neighbour: 3
# gnnheads: 2

# # MBR
# mbrloss: true
# mbrbeam: 5
# mbrnbest: 5
# mbrlambda: 1.0
# mweweight: 1.0
# mbrrareweight: 1.0
# cfm-mbr-start: 19
# mbruseKB: true
