# network architecture
backend: pytorch
model-module: espnet.nets.pytorch_backend.e2e_asr_cfmlas:E2E
# encoder related
elayers: 12
eunits: 1024
eprojs: 256 # this must equal to transformer-adim
transformer-adim: 256
transformer-aheads: 4
transformer-attn-dropout-rate: 0.1
transformer-input-layer: conv2d
transformer-encoder-activation-type: swish
transformer-encoder-pos-enc-layer-type: rel_pos
transformer-encoder-selfattn-layer-type: rel_selfattn
macaron-style: true
use-cnn-module: true
cnn-module-kernel: 31
# decoder related
dlayers: 1
dunits: 1024
# attention related
adim: 1024
atype: location
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.0

# label smoothing
lsm-type: unigram
lsm-weight: 0.1
dropout-rate: 0.1
dropout-rate-decoder: 0.1
weight-decay: 0.0
# ema-decay: 0.999
context-residual: true

# minibatch related
batch-size: 20
maxlen-in: 512
maxlen-out: 150
maxioratio: 300
minioratio: 6

# optimization related
sortagrad: 0
accum-grad: 6
grad-clip: 5
opt: noam
epochs: 80
patience: 0
# weight-noise-std: 0.00
# weight-noise-start: 20000
transformer-lr: 2.5
transformer-warmup-steps: 25000

# scheduled sampling option
sampling-probability: 0.0
# report-interval-iters: 1

# KB related
# meetingpath: /home/gs534/rds/hpc-work/work/Librispeech/data_100/KBs/LibriKBRare_unigram600suffix/rareword_f15.txt
# meetingKB: true
# dictfile: /home/gs534/rds/hpc-work/work/Librispeech/data_100/KBs/bpe_dict_unigram600suffix.txt
# lm-odim: 256
# KBlextree: true
# PtrGen: true
# PtrSche: 0
# # PtrKBin: true
# # init-full-model: /home/dawna/gs534/espnet/egs/ami/ami_transformer/exp/ami_train_cfm_KB200_drop/results/model.acc.best
# # init-full-model: /home/dawna/gs534/espnet/egs/ami/ami_transformer/exp/ami_train_conformer_unigram200suffix_specaug/results/model.acc.best
# acousticonly: true
# attn_dim: 256
# KBmaxlen: 500
# KBminlen: 500
# randomKBsample: true
# # DBinput: true
# # DBmask: 0.1
# DBdrop: 0.3
# # dynamicKBs: 0
# # smoothprob: 0.0
# # ILMTfactor: 0.1
# # treetype: gcn

# MBR
# mbrloss: true
# mbrbeam: 5
# mbrnbest: 5
# mbrlambda: 1.0
# mweweight: 0.5
# mbrrareweight: 0.5
# # use-wp-errors: true
# cfm-mbr-start: 15
# mbruseKB: false

# MM
# modalitymatch: true
# mmfactor: 0.25
# allseq: true
# clsfactor: 1.0
# usedeconly: true
# bertwpm: false
# pooling: max
