# minibatch related
batch-size: 36
maxlen-in: 512
maxlen-out: 150
maxioratio: 300
minioratio: 6

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
save-interval-iters: 0
sortagrad: 0
opt: adadelta
epochs: 100
patience: 3
eps: 5e-9
accum-grad: 4
# ema-decay: 0.999

# network architecture
etype: vggblstmp
elayers: 4
eunits: 1024
eprojs: 2048
subsample: "1_1_1_1"
dropout-rate: 0.1

## decoder related
dtype: lstm
dlayers: 2
dunits: 1024
dropout-rate-decoder: 0.1
dropout-rate-embed-decoder: 0.1

## joint network related
joint-dim: 1024

# transducer related
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
include-blank: true
trans-type: warp-rnnt
# debug
# report-interval-iters: 1
#
# MBR
mbrloss: true
mbrbeam: 5
mbrnbest: 5
mbrlambda: 0.0
# mbrGT: true
mweweight: 1.0
mbrrareweight: 0.0
# use-wp-errors: true
# init-full-model: /home/gs534/rds/hpc-work/work/AMI/rnnt_exp/ami_train_baseline_rnnt/results/baseline.ep.10
# init-full-model: /home/gs534/rds/hpc-work/work/AMI/rnnt_exp/ami_train_baseline_rnnt/results/model.loss.best 
init-full-model: /home/gs534/rds/hpc-work/work/AMI/rnnt_exp/ami_train_baseline_rnnt_no_epsdecay/results/model.loss.best
wrt-alignments: true
