# minibatch related
batch-size: 24
maxlen-in: 512
maxlen-out: 150
# maxioratio: 300
# minioratio: 6

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
save-interval-iters: 0
sortagrad: 0
opt: noam
transformer-lr: 2.5
transformer-warmup-steps: 25000
epochs: 120
patience: 0
accum-grad: 5
grad-clip: 5.0
# ema-decay: 0.999

# network architecture
## general
custom-enc-positional-encoding-type: rel_pos
custom-enc-self-attn-type: rel_self_attn
custom-enc-pw-activation-type: swish
## encoder related
etype: custom
custom-enc-input-layer: conv2d
enc-block-arch:
  - type: conformer
    d_hidden: 144
    d_ff: 576
    heads: 4
    macaron_style: True
    use_conv_mod: True
    conv_mod_kernel: 31
    dropout-rate: 0.1
    att-dropout-rate: 0.0
enc-block-repeat: 16
## decoder related
dtype: lstm
dlayers: 1
dunits: 320
dropout-rate-decoder: 0.1
dropout-rate-embed-decoder: 0.1

## joint network related
joint-dim: 320

# transducer related
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
trans-type: warp-rnnt
include-blank: true

# debug
# report-interval-iters: 1
# save-best: false

# KB related
meetingpath: /home/gs534/rds/hpc-work/work/Librispeech/data_100/RNNTKBs/LibriKBRare_unigram600suffix/rareword_f15.txt
meetingKB: true
dictfile: /home/gs534/rds/hpc-work/work/Librispeech/data_100/RNNTKBs/bpe_dict_unigram600suffix.txt
KBlextree: true
PtrGen: true
# PtrKBin: true
PtrSche: 60
# init-full-model: /home/dawna/gs534/espnet-debug/egs/librispeech/rnnt_960/exp/init_models/baseline.ep.9
# init-full-model: exp/librispeech_train_baseline_spec/results/model.acc.best
acousticonly: true
attn_dim: 256
KBmaxlen: 500
KBminlen: 500
randomKBsample: true
# DBinput: true
# DBmask: 0.1
DBdrop: 0.0
# dynamicKBs: 1
# smoothprob: 0.0
# initembed: 256
