# minibatch related
batch-size: 6
maxlen-in: 512
maxlen-out: 150
maxioratio: 300
minioratio: 6

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
save-interval-iters: 0
sortagrad: 0
opt: adadelta
epochs: 100
patience: 0
eps: 5e-9
accum-grad: 1
# ema-decay: 0.999

# network architecture
etype: vggblstmp
elayers: 4
eunits: 1024
eprojs: 2048
subsample: "1_1_1_1"
dropout-rate: 0.1

## decoder related
dtype: lstm
dlayers: 1
dunits: 1024
dec-embed-dim: 1024
dropout-rate-decoder: 0.1
dropout-rate-embed-decoder: 0.1

## joint network related
joint-dim: 1024

# transducer related
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
include-blank: true
trans-type: warp-rnnt
# debug
report-interval-iters: 1
save-interval-iters: 6
sampler: true
#
# init-full-model: /home/gs534/rds/hpc-work/work/Librispeech/rnnt_exp_100/Librispeech100_baseline_rnnt_MWE1.0_Rare0.0_epoch5/results/baseline.ep.7
