# minibatch related
batch-size: 6
maxlen-in: 512
maxlen-out: 150
#maxioratio: 300
#minioratio: 6

# optimization related
criterion: loss
# early-stop-criterion: "validation/main/loss"
save-interval-iters: 0
sortagrad: 0
opt: noam
transformer-lr: 2.5
transformer-warmup-steps: 25000
epochs: 400
patience: 0
accum-grad: 1
grad-clip: 5.0
# ema-decay: 0.999

# network architecture
## general
custom-enc-positional-encoding-type: rel_pos
custom-enc-self-attn-type: rel_self_attn
custom-enc-pw-activation-type: swish
## encoder related
etype: custom
custom-enc-input-layer: conv2d
enc-block-arch:
  - type: conformer
    d_hidden: 144
    d_ff: 576
    heads: 4
    macaron_style: True
    use_conv_mod: True
    conv_mod_kernel: 31
    dropout-rate: 0.1
    att-dropout-rate: 0.0
enc-block-repeat: 16

## decoder related
dtype: lstm
dlayers: 1
dunits: 320
dropout-rate-decoder: 0.1
dropout-rate-embed-decoder: 0.1

## joint network related
joint-dim: 320

# transducer related
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
include-blank: true
trans-type: warp-rnnt
# debug
report-interval-iters: 1
save-interval-iters: 6
sampler: true

# KB related
# meetingpath: /home/gs534/rds/hpc-work/work/AMI/data/rnnt/KBs/AMIKBRare_unigram200RNNT/rareword_f30.txt
# meetingKB: true
# dictfile: /home/gs534/rds/hpc-work/work/AMI/data/rnnt/KBs/bpe_dict_unigram200RNNT.txt
# KBlextree: true
# PtrGen: true
# # PtrKBin: true
# PtrSche: 0
# init-full-model: /home/gs534/rds/hpc-work/work/AMI/rnnt_exp/ami_train_baseline_rnnt/results/baseline.ep.10
# # init-full-model: /home/gs534/rds/hpc-work/work/AMI/rnnt_exp/ami_train_rnnt_KB100_drop_no_epsdecay/results/model.loss.best
# acousticonly: true
# attn_dim: 256
# KBmaxlen: 100
# KBminlen: 100
# randomKBsample: true
# # DBinput: true
# # DBmask: 0.1
# DBdrop: 0.1
# # dynamicKBs: 0
# # smoothprob: 0.0

# MBR
# mbrloss: true
# mbrbeam: 5
# mbrnbest: 5
# mbrlambda: 1.0
# # mbrGT: true
# mweweight: 1.0
# mbrrareweight: 0.0
# # use-wp-errors: true
# init-full-model: /home/gs534/rds/hpc-work/work/AMI/rnnt_exp/ami_train_baseline_rnnt/results/baseline.ep.10
# # init-full-model: /home/gs534/rds/hpc-work/work/AMI/rnnt_exp/ami_train_baseline_rnnt/results/model.loss.best 
# # init-full-model: /home/gs534/rds/hpc-work/work/AMI/rnnt_exp/ami_train_baseline_rnnt_no_epsdecay/results/model.loss.best
# # wrt-alignments: true
